apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-web
spec:
  selector:
    matchLabels:
      app: synergychat-web
  template:
    metadata:
      labels:
        app: synergychat-web
    spec:
      containers:
        - name: synergychat-web
          image: docker.io/bootdotdev/synergychat-web:latest
          envFrom:
            - configMapRef:
                name: synergychat-web-configmap
