apiVersion: v1
kind: ConfigMap
metadata:
  name: synergychat-crawler-configmap
  namespace: crawler
data:
  CRAWLER_DB_PATH: "/cache/db"
  CRAWLER_PORT: "8080"
  CRAWLER_KEYWORDS: "love,death,life,magic"
